### ISSUE TITLE
cifar-10 example？？

### ISSUE THREAD

**Issue by chenjun2hao** [Zhen-Dong/HAWQ#7]
is there have example on cifar-10?
thanks!

**Comment by Zhen-Dong** [comment]
Hi, thanks for your interest. There are no cifar-10 experiments in HAWQ because generally cifar-10 results are very dependent on fine-tuning. However, all the dataset related codes are in quant_train.py and are easy to change. 
For example, https://github.com/Zhen-Dong/HAWQ/blob/main/quant_train.py#L391
And the training strategy may also need to be modified accordingly (such as lr, batch size, epochs, etc).

**Comment by chenjun2hao** [comment]
thanks for your reply！
